


class PromptEngineer:
    def __init__(self):
        self.personligt_brev = "Mitt namn är [Första Namn] [Efternamn] och jag gick på Industritekniska programmet med svets som inriktning på Nordenbergsskolan i Olofström. Där tränade jag upp skicklighet och kompetens att använda svarv,fräs,kallsåg,bocka,valsar och en rad olika maskiner inom metalbearbetning,behärskar olika svetsmetoder som MMA, TIG, MIG/MAG , gaslödning  rörtrådssvetsning samt robotsvetsning och kan utföra dessa momment med säkerhet och kvalitet i åtanke,bänkarbete,cad med inventor och solidworks. Jag gick också på Automationsingenjörs programmet på Yrkeshögskolan Syd. Lite jag har lärt mig är projektledning och elkonstruktion och hur man kopplar motorer ,felsöker, läser kretsscheman och har lärt mig pneumatik, hydraulik där också (har bara kopplat pneumatik fysiskt), jag har lärt mig hur man programmerar plc och har programmerat robotar och har även använt robotstudio. och gått igenom säkerheten på robotceller som,CE märkning,riskanalys,riskåtgärd och vilka säkerhet komponenter man ska ha. Kan även dom tekniska termerna på engelska på ritningsläsning,säkerhet komponenter och elektriska komponenter. Jag är en mycket driven och teknik intresserad kille som har det lätt för att lära sig. Jag är van och trivs bra med ett högt arbetstempo och jag ser alltid till att ha saker att göra. Jag har också praktiserat hos verktygsmakarna (sammanlagt 119 dagar). Där fick jag hjälpa till slipa verktyg, fixa verktyg, fläckar, koppla om tryckluften i verktyget, har svetsat verktyg, lägga in plåtar i pressen med mera. jag har också truckkort A-B och har arbetat inom lager hantering också där truckkörning förekom. Har tillgång till bil samt körkort B. Med dessa erfarenheter i åtanke, vill jag tacka för möjligheten att presentera mig själv och mina kvalifikationer. Jag är övertygad om att mina tekniska kunskaper och praktiska erfarenheter kan vara till stor nytta för [Företagets] fortsatta framgång. Jag uppskattar verkligen att ni tagit er tid att överväga min ansökan, och jag ser fram emot möjligheten att i en personlig intervju få diskutera hur jag kan bidra till ert team och era mål. Tack än en gång för att ni beaktar min ansökan. Jag hoppas på att få möjligheten att ytterligare diskutera min potentiella roll hos [Företagets]. Med vänlig hälsning, [Första Namn] [Efternamn]"
    def GeneratePrompt(self,företag_name,arbetsroll):
        print(f"Snälla hjälp mig att skriva ett riktat personligt brev för företaget {företag_name} och rollen {arbetsroll}, som framhäver mitt intresse för att gå med i företaget och hur mina kunskaper och erfarenheter gör mig till en stark kandidat. Här är några nyckelpunkter om min bakgrund och motivation för att söka tjänsten: [Relevant erfarenhet och kvalifikationer], [Skäl till intresse för företaget] och [Exempel på kompetens och erfarenheter som ligger i linje med företagets värderingar].")


